[tool.pyright]
include = [
    "/opt/miniconda3/",
    "/opt/miniconda3/lib/python3.12/site-packages",
    "src"]

# ignore = ["bin"]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.12"
pythonPlatform = "Linux"
